server:
  port: 8086
  

spring:  datasource:    url: jdbc:oracle:thin:@localhost:1521:orcl
    password: password2
    username: homeuser
    driver-class-name: oracle.jdbc.OracleDriver  jpa:    hibernate:      ddl-auto: update    show-sql: true    database-platform: org.hibernate.dialect.Oracle12cDialect
      application:    name: VACCINATION-CENTER-SERVICE